---
abstract: ~
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: perl5::ingy
name: perl5-ingy
no_index:
  directory:
    - inc
    - t
requires:
  IO::All: 0.41
  perl: 5.10.0
  perl5: 0.03
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/perl5-ingy-pm.git
version: 0.03
