---
abstract: "Ingy's Favorite Perl 5 Feature Set"
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: perl5::ingy
name: perl5-ingy
no_index:
  directory:
    - inc
    - t
requires:
  Capture::Tiny: 0.11
  IO::All: 0.43
  XXX: 0.17
  YAML::XS: 0.35
  perl: 5.10.0
  perl5: 0.08
resources:
  homepage: http://github.com/ingydotnet/perl5-ingy-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/perl5-ingy-pm.git
version: 0.07
